# Generated by Django 4.0.3 on 2022-03-11 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_mongodb_connector', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
